spring:
  datasource:
      url: jdbc:mysql://localhost:3306/test?useSSL=false
      username: root
      password: root
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update

## App Properties
app :
  jwtSecret : JWTSuperSecretKey
  jwtExpirationInMs : 604800000
logging:
  level:
    org:
      hibernate:
        SQL: debug
